# version:   "0000--11-Sep-2022"
copyright:   "2022"
author:      "DavidChristianto"
name:        "David Christianto"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/DavidChristianto/os222"
myloglink:   "/TXT/mylog.txt"
